from fastapi import FastAPI
import requests
import time

app = FastAPI()

LLAMA_API = "http://127.0.0.1:8080/completion"

# SAFETY FILTER
def is_safe(text):
    banned = [
        "password", "otp", "credit card", "bank details",
        "hack", "illegal", "exploit", "bypass",
        "self harm", "suicide"
    ]

    for word in banned:
        if word in text.lower():
            return False

    return True

# PROMPT CLEANER
def clean_prompt(query):
    return f"""
You are a factual AI assistant.

Rules:
- Give correct and verified information
- If unsure, say "I am not sure"
- Do not guess or hallucinate
- Answer clearly and concisely

Question: {query}
Answer:
"""

def validate_response(response):
    bad_words = ["italian noodle", "maybe", "i think"]
    for w in bad_words:
        if w in response.lower():
            return "The model may be uncertain. Please verify this information."
    return response

def run_model(prompt):
    start = time.time()

    payload = {
        "prompt": prompt,
        "n_predict": 50
    }

    response = requests.post(LLAMA_API, json=payload)
    result = response.json().get("content", "")

    end = time.time()

    return result, round(end - start, 2)

@app.get("/ask")
def ask(query: str):
    if not is_safe(query):
        return {"response": "Request blocked for safety reasons."}

    cleaned = clean_prompt(query)
    response, latency = run_model(cleaned)

    return {
        "response": response,
        "latency_seconds": latency,
        "note": "Response generated by small offline AI model; may contain minor inaccuracies."
    }